'use strict';
const $=id=>document.getElementById(id);
const escapeHtml=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const codeExtensions=new Set('js jsx mjs cjs ts tsx py pyw pyi java c h cpp hpp cc cs go rs rb php swift kt kts scala lua r sh bash zsh ps1 bat cmd sql vue svelte html htm css scss sass less'.split(' '));
const configExtensions=new Set('json jsonc jsonl yaml yml toml ini conf cfg xml csv tsv properties env lock'.split(' '));
const icon=name=>{const base=name.split(/[\\/]/).pop();let ext=base.includes('.')?base.split('.').pop().toLowerCase():'';const kind=codeExtensions.has(ext)||['Dockerfile','Makefile'].includes(base)?'code':configExtensions.has(ext)?'config':['pdf','docx','docs','md','txt'].includes(ext)?ext:'txt';const label=(ext|| (kind==='code'?'CODE':'TEXT')).toUpperCase().slice(0,4);return `<span class="file-icon ${kind}" title="${escapeHtml(base)}">${escapeHtml(label)}</span>`};
const size=n=>n<1024?`${n} B`:n<1048576?`${(n/1024).toFixed(1)} KB`:`${(n/1048576).toFixed(1)} MB`;
let currentFolder='', currentDoc=null, editing=false, selected=[], uploadJob=null, listVersion=0;
let toastTimer;
let folderCache=[], moving=null, renderedMode=false;
let expanded=new Set();
try { expanded=new Set(JSON.parse(localStorage.getItem('rag-expanded-folders')||'[]')); } catch {}
const renderable=new Set(['.md','.markdown','.mdown','.json','.csv','.tsv']);
function toast(message){$('toast').textContent=message;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,5500)}
async function api(path,options={}){const r=await fetch('/api'+path,{...options,headers:{'X-RAG-UI':'1',...(options.body instanceof FormData?{}:{'Content-Type':'application/json'}),...options.headers}});let result=await r.json();if(!r.ok)throw Error(typeof result.detail==='string'?result.detail:JSON.stringify(result.detail||result));return result}
function dirty(){return editing&&currentDoc&&$('editor').value!==currentDoc.content.replace(/\r\n?/g,'\n')}
function canLeave(){return !dirty()||confirm('有尚未保存的修改，确定放弃吗？')}
function crumbs(folder,docName=''){let parts=folder?folder.split('/'):[];let values=[{name:window.uiText?window.uiText('知识库'):'知识库',path:''},...parts.map((name,i)=>({name,path:parts.slice(0,i+1).join('/')}))];$('breadcrumbs').innerHTML=values.map(x=>`<button class="crumb" data-folder="${escapeHtml(x.path)}">${escapeHtml(x.name)}</button>`).join('<span class="crumb-separator">/</span>')+(docName?`<span class="crumb-separator">/</span><span>${escapeHtml(docName)}</span>`:'')}
async function stats(){let s=await api('/status');$('docCount').textContent=s.documents;$('folderCount').textContent=s.folders;$('chunkCount').textContent=s.chunks}
function view(name){$('libraryView').hidden=name!=='library';$('searchView').hidden=name!=='search';$('documentView').hidden=name!=='document';$('libraryActions').hidden=name!=='library';$('stats').hidden=name==='document';$('navDocs').classList.toggle('active',name!=='search');$('navSearch').classList.toggle('active',name==='search')}
async function list(){const v=++listVersion;const q=$('docSearch').value.trim();const r=await api('/list?folder='+encodeURIComponent(currentFolder)+'&q='+encodeURIComponent(q));if(v!==listVersion)return;
folderCache=r.folders;renderTree();
const child=r.folders.filter(f=>f.path&&f.path.split('/').slice(0,-1).join('/')===currentFolder);
$('folderGrid').innerHTML=q?'':child.map(f=>`<div class="folder-card" tabindex="0" role="button" data-folder="${escapeHtml(f.path)}">${folderIcon(f.path,false)}<span><strong>${escapeHtml(f.path==='未分类'&&window.uiText?window.uiText('未分类'):f.path.split('/').pop())}</strong><small>${f.count} 个直属文档${f.path==='未分类'?' · 始终检索':''}</small></span>${f.path==='未分类'?'':`<span class="folder-actions"><button data-move-folder="${escapeHtml(f.path)}" aria-label="移动文件夹 ${escapeHtml(f.path)}">移动</button><button data-delete-folder="${escapeHtml(f.path)}" aria-label="删除文件夹 ${escapeHtml(f.path)}">×</button></span>`}</div>`).join('');
$('documents').innerHTML=r.documents.map(d=>`<tr><td><button class="file-title" data-doc="${d.id}">${icon(d.name)}<span>${escapeHtml(d.name)}</span></button></td><td>${escapeHtml(d.folder||'根目录')}</td><td>${size(d.size)}</td><td>${new Date(d.updated).toLocaleString(window.uiLocale?window.uiLocale():'zh-CN',{year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'})}</td><td><button class="row-move" data-move-doc="${d.id}">移动</button><button class="row-delete" data-delete-doc="${d.id}" data-name="${escapeHtml(d.name)}">删除</button></td></tr>`).join('');
$('emptyState').hidden=!!r.documents.length;$('emptyState').querySelector('h3').textContent=q?'没有找到匹配的文档':'当前目录暂无直属文档';$('emptyState').querySelector('p').textContent=q?'试试其他名称或正文关键词。':'上传文件或整个文件夹，开始积累你的知识。';$('listTitle').textContent=q?`搜索结果 · ${r.documents.length}`:currentFolder?(currentFolder==='未分类'&&window.uiText?window.uiText('未分类'):currentFolder.split('/').pop()):'全部资料';$('listNote').textContent=q?'在所有目录的名称和正文中搜索，最多展示 300 个结果。':'点击文档进入只读预览；编辑保存后自动更新检索内容。';}
async function navigate(folder){if(!canLeave())return;currentFolder=folder;revealFolder(folder);currentDoc=null;editing=false;$('docSearch').value='';view('library');$('pageTitle').textContent=folder?(folder==='未分类'&&window.uiText?window.uiText('未分类'):folder.split('/').pop()):'文档资料库';$('pageSubtitle').textContent='整理你的知识，让每一次回答都有据可循。';crumbs(folder);history.replaceState(null,'','/');await Promise.all([list(),stats()])}
async function openDoc(id){if(!canLeave())return;const d=await api('/documents/'+id);currentDoc=d;editing=false;renderedMode=false;currentFolder=d.folder;revealFolder(d.folder);renderTree();view('document');$('pageTitle').textContent=d.name;$('pageSubtitle').textContent='从原文到知识，让内容始终保持最新。';crumbs(d.folder,d.name);$('previewText').classList.remove('rendered');$('previewText').textContent=d.content;$('editor').value=d.content;$('docWarning').textContent=d.warning;$('docWarning').hidden=!d.warning;$('docMeta').textContent=`版本 ${d.version} · ${d.content.length.toLocaleString()} 字符`;$('downloadOriginal').href='/api/documents/'+id+'/original';editMode(false);history.replaceState(null,'','/?doc='+id)}
function editMode(value){editing=value;$('previewText').hidden=value;$('editorPanel').hidden=!value;$('editDoc').hidden=value;$('cancelEdit').hidden=!value;$('saveDoc').hidden=!value;$('moveCurrentDoc').hidden=value;$('showRendered').hidden=value||!renderable.has(currentDoc.extension)||renderedMode;$('showSource').hidden=value||!renderedMode;$('previewBadge').textContent=value?'编辑解析文本':renderedMode?'渲染预览':'只读源码';if(value){syncEditor();$('editor').focus()}}
function openFolderDialog(){$('folderName').value='';$('folderDialog').showModal();$('folderName').focus()}
function openUpload(){selected=[];renderSelection();$('uploadTarget').textContent='上传到：知识库'+(currentFolder?' / '+currentFolder:'');$('uploadDialog').showModal()}
function renderSelection(){$('selectionCount').textContent=selected.length?`${selected.length} 个文件 · ${size(selected.reduce((n,x)=>n+x.file.size,0))}`:'尚未选择文件';$('selectedFiles').innerHTML=selected.slice(0,100).map(x=>`<div class="selected-row"><span>${icon(x.path)}${escapeHtml(x.path)}</span><span>${size(x.file.size)}</span></div>`).join('')+(selected.length>100?`<p>另有 ${selected.length-100} 个文件</p>`:'');$('uploadStart').disabled=!selected.length}
function addFiles(files){const added=Array.from(files).map(file=>({file,path:file.webkitRelativePath||file.name}));const keys=new Set(selected.map(x=>x.path));for(const x of added){if(!keys.has(x.path)){selected.push(x);keys.add(x.path)}}renderSelection()}
async function trackJob(id){while(uploadJob===id){let j=await api('/jobs/'+id);$('progressBar').value=j.completed/j.total*100;$('progressTitle').textContent=j.state==='done'?'导入完成':'正在解析并建立索引';const errors=j.items.filter(x=>x.status==='error');$('progressText').textContent=`已处理 ${j.completed} / ${j.total} · 成功 ${j.completed-errors.length} · 失败 ${errors.length}`;$('progressErrors').textContent=errors.map(x=>x.path+'：'+x.error).join('\n');if(j.state==='done'){uploadJob=null;await stats();if(!$('libraryView').hidden)await list();toast(errors.length?'导入完成，部分文件失败，请查看导入记录':'文档已入库，可以开始检索');break}await new Promise(r=>setTimeout(r,1000))}}
async function upload(){if(!selected.length)return;const target=currentFolder;const data=new FormData();selected.forEach(x=>data.append('files',x.file,x.file.name));data.append('paths',JSON.stringify(selected.map(x=>x.path)));data.append('folder',target);$('uploadStart').disabled=true;$('uploadStart').textContent='正在上传…';try{let j=await api('/upload',{method:'POST',body:data});$('uploadDialog').close();$('uploadProgress').hidden=false;$('progressErrors').textContent='';$('progressBar').value=0;uploadJob=j.job_id;await trackJob(uploadJob)}finally{$('uploadStart').disabled=false;$('uploadStart').textContent='开始上传'}}
async function runSearch(){const query=$('ragQuery').value.trim();if(!query)return toast('请输入检索问题');$('runSearch').disabled=true;$('runSearch').textContent='检索中…';try{const r=await api('/search',{method:'POST',body:JSON.stringify({query,scope:document.querySelector('input[name="scope"]:checked').value})});$('searchResults').innerHTML=`<p class="route-note">${r.scope==='all'?'全库检索':'自动分类'} · ${escapeHtml(r.selected_categories.map(x=>x||'根目录').join(' / ')||'未找到相关目录')} · ${r.results.length} 个片段</p>`+r.results.map(x=>`<article class="result-card"><header><button data-doc="${x.document_id}">${escapeHtml(x.filename)}</button><small>解析文本 L${x.start_line}–${x.end_line} · v${x.version}</small></header><pre>${escapeHtml(x.content)}</pre><small>${escapeHtml(x.category||'根目录')} · 语义 ${x.semantic_score} · BM25 ${x.keyword_score}</small></article>`).join('')+(!r.results.length?'<div class="empty"><h3>没有找到相关资料</h3><p>请调整问题，或明确选择检索所有文档。</p></div>':'')}finally{$('runSearch').disabled=false;$('runSearch').textContent='检索知识'}}
function guard(fn){return (...args)=>{try{return Promise.resolve(fn(...args)).catch(e=>toast(e.message))}catch(e){toast(e.message)}}}
document.addEventListener('click',guard(async e=>{let action=e.target.closest('[data-toggle]');if(action){const path=action.dataset.toggle;expanded.has(path)?expanded.delete(path):expanded.add(path);saveExpanded();renderTree();return}action=e.target.closest('[data-move-doc]');if(action){await openMove('document',action.dataset.moveDoc);return}action=e.target.closest('[data-move-folder]');if(action){await openMove('folder',action.dataset.moveFolder);return}let t=e.target.closest('[data-delete-doc]');if(t){if(confirm(`删除“${t.dataset.name}”？文档及其检索索引将一起删除。`)){await api('/documents/'+t.dataset.deleteDoc,{method:'DELETE'});await Promise.all([list(),stats()]);toast('文档已删除')}return}
t=e.target.closest('[data-delete-folder]');if(t){e.stopPropagation();if(confirm(`删除“${t.dataset.deleteFolder}”及其所有子目录和文档？`)){await api('/folders?path='+encodeURIComponent(t.dataset.deleteFolder)+'&recursive=true',{method:'DELETE'});await Promise.all([list(),stats()]);toast('文件夹已删除')}return}
t=e.target.closest('[data-folder]');if(t){await navigate(t.dataset.folder);return}t=e.target.closest('[data-doc]');if(t){await openDoc(t.dataset.doc);return}t=e.target.closest('[data-close]');if(t)$(t.dataset.close).close()}));
document.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.classList.contains('folder-card')){e.preventDefault();guard(()=>navigate(e.target.dataset.folder))()}});
$('navDocs').onclick=guard(()=>navigate(''));
$('navSearch').onclick=()=>{if(!canLeave())return;editing=false;view('search');$('pageTitle').textContent='知识检索';$('pageSubtitle').textContent='从相关分类中召回原文，查看每一个答案的依据。';crumbs('');history.replaceState(null,'','/');$('ragQuery').focus()};
$('newFolder').onclick=openFolderDialog;$('sidebarNew').onclick=openFolderDialog;
$('folderForm').onsubmit=guard(async e=>{e.preventDefault();const name=$('folderName').value.trim();if(name.includes('/')||name.includes('\\'))throw Error('请输入单个文件夹名称');await api('/folders',{method:'POST',body:JSON.stringify({path:[currentFolder,name].filter(Boolean).join('/')})});$('folderDialog').close();await Promise.all([list(),stats()]);toast('文件夹已创建')});
$('uploadOpen').onclick=openUpload;$('chooseFiles').onclick=()=>$('filesInput').click();$('chooseFolder').onclick=()=>$('folderInput').click();$('filesInput').onchange=e=>{addFiles(e.target.files);e.target.value=''};$('folderInput').onchange=e=>{addFiles(e.target.files);e.target.value=''};$('uploadStart').onclick=guard(upload);
$('dropzone').ondragover=e=>{e.preventDefault();$('dropzone').classList.add('dragging')};$('dropzone').ondragleave=()=>$('dropzone').classList.remove('dragging');$('dropzone').ondrop=e=>{e.preventDefault();$('dropzone').classList.remove('dragging');addFiles(e.dataTransfer.files)};
$('editDoc').onclick=()=>editMode(true);$('cancelEdit').onclick=()=>{if(canLeave()){$('editor').value=currentDoc.content;editMode(false)}};
$('saveDoc').onclick=guard(async()=>{$('saveDoc').disabled=true;$('saveDoc').textContent='正在更新索引…';try{let d=await api('/documents/'+currentDoc.id,{method:'PUT',body:JSON.stringify({content:$('editor').value,version:currentDoc.version})});currentDoc=d;editing=false;await openDoc(d.id);await stats();toast('修改已保存，检索索引已更新')}finally{$('saveDoc').disabled=false;$('saveDoc').textContent='保存并更新索引'}});
let debounce;$('docSearch').oninput=()=>{clearTimeout(debounce);debounce=setTimeout(guard(list),250)};
$('runSearch').onclick=guard(runSearch);$('ragQuery').onkeydown=e=>{if(e.key==='Enter')guard(runSearch)()};$('closeProgress').onclick=()=>$('uploadProgress').hidden=true;
window.addEventListener('beforeunload',e=>{if(dirty()){e.preventDefault();e.returnValue=''}});

function folderIcon(path,open){
    const type=path==='未分类'?'inbox':!path?'root':open?'open':'closed';
    const shapes={inbox:'<path d="M4 4h16v16H4z"/><path d="M4 13h5l2 3h2l2-3h5"/>',root:'<path d="M3 5h7l2 2h9v14H3z"/><path d="M7 12h10M7 16h7"/>',closed:'<path d="M3 6h7l2 2h9v12H3z"/>',open:'<path d="M3 10V6h7l2 2h8v3"/><path d="M3 11h19l-3 9H3z"/>'};
    return `<svg class="directory-icon ${type}" viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linejoin="round">${shapes[type]}</svg>`;
}
function saveExpanded(){try{localStorage.setItem('rag-expanded-folders',JSON.stringify([...expanded]))}catch{}}
function revealFolder(path){const parts=path.split('/');for(let i=1;i<=parts.length;i++)if(path)expanded.add(parts.slice(0,i).join('/'));saveExpanded()}
function renderTree(){
    const children=new Map();for(const f of folderCache){if(!f.path)continue;const parent=f.path.split('/').slice(0,-1).join('/');if(!children.has(parent))children.set(parent,[]);children.get(parent).push(f)}
    function branch(parent,level){return (children.get(parent)||[]).map(f=>{const has=(children.get(f.path)||[]).length>0,open=expanded.has(f.path);return `<div role="treeitem" aria-level="${level}" aria-selected="${f.path===currentFolder}" ${has?`aria-expanded="${open}"`:''}><div class="tree-row ${f.path===currentFolder?'current':''}">${has?`<button class="tree-toggle" data-toggle="${escapeHtml(f.path)}" aria-label="${open?'折叠':'展开'} ${escapeHtml(f.path)}">${open?'⌄':'›'}</button>`:'<span class="tree-spacer"></span>'}<button class="tree-name" data-folder="${escapeHtml(f.path)}" title="${escapeHtml(f.path)}">${folderIcon(f.path,open)}<span>${escapeHtml(f.path==='未分类'&&window.uiText?window.uiText('未分类'):f.path.split('/').pop())}</span>${f.path==='未分类'?'<small>常查</small>':''}</button></div>${has&&open?`<div class="tree-group" role="group">${branch(f.path,level+1)}</div>`:''}</div>`}).join('')}
    $('tree').innerHTML=`<div class="tree-row ${currentFolder===''?'current':''}"><span class="tree-spacer"></span><button class="tree-name" data-folder="">${folderIcon('',false)}<span>${window.uiText?window.uiText('全部资料'):'全部资料'}</span></button></div>`+branch('',1);
}
$('expandTree').onclick=()=>{expanded=new Set(folderCache.map(f=>f.path));saveExpanded();renderTree()};
$('collapseTree').onclick=()=>{expanded.clear();saveExpanded();renderTree()};
function syncEditor(){const editor=$('editor'),value=editor.value;const count=value.split('\n').length;$('lineNumbers').textContent=Array.from({length:count},(_,i)=>i+1).join('\n');syncCursor();$('lineNumbers').scrollTop=editor.scrollTop}
function syncCursor(){const e=$('editor'),before=e.value.slice(0,e.selectionStart),lines=before.split('\n');$('editorStatus').textContent=`行 ${lines.length}，列 ${lines[lines.length-1].length+1} · 共 ${e.value.split('\n').length} 行 · Tab 缩进`}
$('editor').addEventListener('input',syncEditor);$('editor').addEventListener('scroll',()=>{$('lineNumbers').scrollTop=$('editor').scrollTop});
for(const event of ['click','keyup','select'])$('editor').addEventListener(event,syncCursor);
$('editor').addEventListener('keydown',e=>{if(e.key==='Tab'){e.preventDefault();const input=$('editor');input.setRangeText('    ',input.selectionStart,input.selectionEnd,'end');syncEditor()}});
$('showRendered').onclick=guard(async()=>{if(!currentDoc)return;const id=currentDoc.id,version=currentDoc.version;$('showRendered').disabled=true;try{const r=await api('/documents/'+id+'/render');if(!currentDoc||currentDoc.id!==id||editing)return;if(r.version!==version)throw Error('文档已更新，请重新打开后预览');$('previewText').innerHTML=r.html;$('previewText').classList.add('rendered');renderedMode=true;editMode(false)}finally{$('showRendered').disabled=false}});
$('showSource').onclick=()=>{$('previewText').textContent=currentDoc.content;$('previewText').classList.remove('rendered');renderedMode=false;editMode(false)};
async function openMove(kind,id){if(!canLeave())return;const listing=await api('/list');const doc=kind==='document'?await api('/documents/'+id):null;moving={kind,id,version:doc?.version};const source=kind==='folder'?id:doc.folder;const currentParent=kind==='folder'?source.split('/').slice(0,-1).join('/'):source;
const folders=listing.folders.filter(f=>kind!=='folder'||(f.path!==source&&!f.path.startsWith(source+'/')));$('moveTarget').innerHTML=folders.map(f=>`<option value="${escapeHtml(f.path)}" ${f.path===currentParent?'selected':''}>${escapeHtml(f.path||'根目录')}</option>`).join('');$('moveDescription').textContent='移动'+(kind==='folder'?'文件夹及其全部内容：'+source:'文档：'+doc.name);$('moveDialog').showModal()}
$('moveCurrentDoc').onclick=guard(()=>openMove('document',currentDoc.id));
$('moveForm').onsubmit=guard(async e=>{e.preventDefault();if(!moving)return;$('confirmMove').disabled=true;$('confirmMove').textContent='移动并更新索引…';try{const target=$('moveTarget').value;let destination=target;if(moving.kind==='document'){await api('/documents/'+moving.id+'/move',{method:'POST',body:JSON.stringify({target_folder:target,version:moving.version})})}else{const r=await api('/folders/move',{method:'POST',body:JSON.stringify({source:moving.id,target_parent:target})});destination=r.target}editing=false;$('moveDialog').close();await navigate(destination);toast('移动完成，索引已更新')}finally{$('confirmMove').disabled=false;$('confirmMove').textContent='确认移动'}});

(async()=>{const id=new URLSearchParams(location.search).get('doc');await navigate('');if(id)await openDoc(id)})().catch(e=>toast('无法连接本地服务：'+e.message));
